//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbal.yah_varmalayam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseLineItem
    {
        public int Id { get; set; }
        public string PurchaseLineItemCode { get; set; }
        public int PurchaseId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal PurchaseAmount { get; set; }
        public decimal GrossAmount { get; set; }
        public Nullable<decimal> GST { get; set; }
        public decimal NetAmount { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual PurchaseHeader PurchaseHeader { get; set; }
    }
}
