//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbal.yah_varmalayam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseHeader()
        {
            this.PurchaseLineItems = new HashSet<PurchaseLineItem>();
        }
    
        public int Id { get; set; }
        public string PurchaseCode { get; set; }
        public string ClientName { get; set; }
        public Nullable<long> ClientMobileNumber { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal TotalGrossAmount { get; set; }
        public decimal TotalDiscount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public decimal TotalNetAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal DueAmount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ClientInvoiceNumber { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public decimal TotalPurchaseAmount { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseLineItem> PurchaseLineItems { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
