//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbal.yah_varmalayam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseLineItem
    {
        public int Id { get; set; }
        public string PurchaseLineItemCode { get; set; }
        public int PurchaseId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal GrossAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public decimal NetAmount { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
    
        public virtual PurchaseHeader PurchaseHeader { get; set; }
    }
}
