//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbal.yah_varmalayam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLineItem
    {
        public int Id { get; set; }
        public string SalesLineItemCode { get; set; }
        public int SalesId { get; set; }
        public int ProductId { get; set; }
        public decimal ConfigSellingPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal SalesAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal GrossAmount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public decimal NetAmount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual SalesHeader SalesHeader { get; set; }
    }
}
