//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbal.yah_varmalayam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesHeader()
        {
            this.SalesLineItems = new HashSet<SalesLineItem>();
        }
    
        public int Id { get; set; }
        public string SalesCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public System.DateTime SalesDate { get; set; }
        public decimal TotalSalesAmount { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalGrossAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public decimal TotalNetAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal DueAmount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string CustomerMobileNumbers { get; set; }
        public string CustomerGSTIN { get; set; }
        public string CustomerAddress { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLineItem> SalesLineItems { get; set; }
    }
}
